# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/pdrego/Downloads/Final_Project/1_2_9_SD_DMA/vivado_DMA/top.xdc

# Block Designs: bd/DMA_block_design/DMA_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design || ORIG_REF_NAME==DMA_block_design} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_processing_system7_0_0/DMA_block_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_processing_system7_0_0 || ORIG_REF_NAME==DMA_block_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_axi_dma_0_0/DMA_block_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_axi_dma_0_0 || ORIG_REF_NAME==DMA_block_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_ps7_0_axi_periph_0/DMA_block_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==DMA_block_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_rst_ps7_0_100M_0/DMA_block_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==DMA_block_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_axis_data_fifo_0_0/DMA_block_design_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_axis_data_fifo_0_0 || ORIG_REF_NAME==DMA_block_design_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_xlconcat_0_0/DMA_block_design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_xlconcat_0_0 || ORIG_REF_NAME==DMA_block_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_smartconnect_0_0/DMA_block_design_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_smartconnect_0_0 || ORIG_REF_NAME==DMA_block_design_smartconnect_0_0} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_clk_wiz_0_0/DMA_block_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_clk_wiz_0_0 || ORIG_REF_NAME==DMA_block_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_OLED_0_0/DMA_block_design_OLED_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_OLED_0_0 || ORIG_REF_NAME==DMA_block_design_OLED_0_0} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_system_ila_0_0/DMA_block_design_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_system_ila_0_0 || ORIG_REF_NAME==DMA_block_design_system_ila_0_0} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_design_1_wrapper_0_0/DMA_block_design_design_1_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_design_1_wrapper_0_0 || ORIG_REF_NAME==DMA_block_design_design_1_wrapper_0_0} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_clk_wiz_2/DMA_block_design_clk_wiz_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_clk_wiz_2 || ORIG_REF_NAME==DMA_block_design_clk_wiz_2} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_util_vector_logic_0_0/DMA_block_design_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_util_vector_logic_0_0 || ORIG_REF_NAME==DMA_block_design_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/DMA_block_design/ip/DMA_block_design_auto_pc_0/DMA_block_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_block_design_auto_pc_0 || ORIG_REF_NAME==DMA_block_design_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/pdrego/Downloads/Final_Project/1_2_9_SD_DMA/vivado_DMA/vivado_DMA.gen/sources_1/bd/DMA_block_design/DMA_block_design_ooc.xdc
